name: conda_vimsegdet_mmcv2x_py310
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py310h7354ed3_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - filelock=3.20.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - ftfy=6.3.1=pyhd8ed1ab_1
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.2=py310ha78e65c_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h1b119a7_104
  - icu=75.1=he02047a_0
  - idna=3.11=py310h06a4308_0
  - imath=3.2.2=hde8ca8f_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jasper=4.2.8=he3c4edf_0
  - jinja2=3.1.6=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp21.1=21.1.7=default_h99862b1_1
  - libclang13=21.1.7=default_h746c552_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.4.0.35=h50d9014_0
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_13
  - libgcc-ng=15.2.0=h69a702a_13
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_13
  - libgfortran5=15.2.0=h68bc16d_13
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h32235b2_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_13
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm21=21.1.7=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopencv=4.12.0=qt6_py310h84e3671_609
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_13
  - libstdcxx-ng=15.2.0=hdf11a46_13
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=py310h06a4308_0
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py310hec850f8_609
  - openexr=3.4.4=he10986b_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h4e0627c_1
  - openjph=0.25.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h5a73078_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - py-opencv=4.12.0=qt6_py310h89973df_609
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h591646f_0
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - regex=2025.11.3=py310h7c4b9e2_1
  - requests=2.32.5=py310h06a4308_1
  - scipy=1.15.2=py310h1d65ade_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h3e344bc_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=py310h06a4308_1
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_ha0e22de_103
  - torchaudio=2.1.2=py310_cu121
  - torchtriton=2.1.0=py310
  - torchvision=0.16.2=py310_cu121
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.6.1=py310h06a4308_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1+computecanada
      - addict==2.4.0+computecanada
      - antlr4-python3-runtime==4.9.3+computecanada
      - anyio==4.12.0
      - black==25.12.0
      - causal-conv1d==1.4.0
      - click==8.3.1+computecanada
      - cloudpickle==3.1.2+computecanada
      - contourpy==1.3.1+computecanada
      - cycler==0.12.1+computecanada
      - detectron2==0.6
      - einops==0.8.1+computecanada
      - exceptiongroup==1.3.1
      - fonttools==4.61.0
      - fsspec==2025.12.0+computecanada
      - fvcore==0.1.5.post20220512+computecanada
      - grpcio==1.67.0+computecanada
      - h11==0.16.0+computecanada
      - hf-xet==1.2.0+computecanada
      - httpcore==1.0.9+computecanada
      - httpx==0.28.1+computecanada
      - huggingface-hub==0.20.3+computecanada
      - hydra-core==1.3.2+computecanada
      - iopath==0.1.9+computecanada
      - kiwisolver==1.4.8+computecanada
      - mamba-ssm==1.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0+computecanada
      - matplotlib==3.10.0+computecanada
      - mdurl==0.1.2+computecanada
      - mmcv==2.1.0
      - mmdet==3.3.0+computecanada
      - mmengine==0.10.1+computecanada
      - mmsegmentation==1.2.2+computecanada
      - mypy-extensions==1.1.0+computecanada
      - ninja==1.11.1+computecanada
      - omegaconf==2.3.0+computecanada
      - packaging==25.0+computecanada
      - pathspec==0.12.1+computecanada
      - pillow-simd==9.5.0.post2+computecanada
      - platformdirs==4.5.1
      - portalocker==3.2.0+computecanada
      - prettytable==3.17.0
      - protobuf==6.33.2
      - pycocotools==2.0.6+computecanada
      - pygments==2.19.2+computecanada
      - pyparsing==3.2.5+computecanada
      - python-dateutil==2.9.0.post0+computecanada
      - pytokens==0.3.0
      - rich==14.2.0+computecanada
      - safetensors==0.5.3+computecanada
      - shapely==2.0.4+computecanada
      - shellingham==1.5.4+computecanada
      - six==1.17.0+computecanada
      - tabulate==0.9.0+computecanada
      - tensorboard==2.20.0+computecanada
      - tensorboard-data-server==0.7.2+computecanada
      - termcolor==3.2.0+computecanada
      - terminaltables==3.1.10+computecanada
      - timm==1.0.22
      - tokenizers==0.15.2
      - tomli==2.3.0
      - tqdm==4.67.1+computecanada
      - transformers==4.38.2
      - typer-slim==0.20.0
      - wcwidth==0.2.14+computecanada
      - werkzeug==3.1.4
      - yacs==0.1.8+computecanada
      - yapf==0.43.0+computecanada
prefix: /home/f7ibrahi/projects/def-wangcs/f7ibrahi/miniconda3/envs/conda_vimsegdet_mmcv2x_py310
