name: conda_vimsegdet_mmcv2x_py310
channels:
  - defaults
dependencies:
  - numpy=1.26
  - python=3.10.19
  - pytorch-cuda=12.1
  - opencv
  - scipy
  - ftfy
  - regex
  - pytorch=2.1
  - sympy
  - torchaudio
  - torchvision
prefix: /home/f7ibrahi/projects/def-wangcs/f7ibrahi/miniconda3/envs/conda_vimsegdet_mmcv2x_py310
